export const RECEIVE_FUTURE_POSTS = 'HOME_PAGE.RECEIVE_FUTURE_POSTS';
export const RECEIVE_NEW_POSTS = 'HOME_PAGE.RECEIVE_NEW_POSTS';
export const RECEIVE_POPULAR_POSTS = 'HOME_PAGE.RECEIVE_POPULAR_POSTS';