export const RECEIVE_POST = 'POST.RECEIVE_POST';
export const FETCHING_POST = 'POST.FETCHING_POST';
export const RECEIVE_ERROR = 'POST.RECEIVE_ERROR';
export const RECEIVE_COMMENTS = 'POST.RECEIVE_COMMENTS';