export const LOGIN = {
    SUCCESS: 'AUTH.LOGIN.SUCCESS',
    FAILED: 'AUTH.LOGIN.FAILED',
};

export const REGISTER = {
    SUCCESS: 'AUTH.REGISTER.SUCCESS',
    FAILED: 'AUTH.REGISTER.FAILED',
};

export const LOGOUT = {
    SUCCESS: 'AUTH.LOGOUT.SUCCESS',
    FAILED: 'AUTH.LOGOUT.FAILED',
};

export const FETCHING = {
    BEGIN: 'AUTH.FETCHING.BEGIN',
    FINISH: 'AUTH.FETCHING.FINISH',
};

export const RESETING = {
    ACCOUNT: 'AUTH.RESETING.ACCOUNT',
    UPDATE_STATUS: 'AUTH.RESETING.UPDATE_STATUS',
};

export const SAVE_ERROR = 'AUTH.SAVE_ERROR';

export const CLEAR_ERROR_MESSAGE = 'AUTH.CLEAR_ERROR_MESSAGE';