export default interface iUser {
    id: number,
    name: string,
    email: string,
    created_at: string,
    updated_at: string,
    auth_type: string,
    user_group: number,
    banned: number,
    allow_mail: number,
    info: string|null,
    foto: string|null,
    fullname: string|null,
    land: string|null,
    favorites: string|null,
    hash: string|null,
    logged_ip: string|null,
    is_old: number,
    requested_removing: number,
}